# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lsp_stats.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='lsp_stats.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0flsp_stats.proto\x1a\x13telemetry_top.proto\"6\n\x08LspStats\x12*\n\x11lsp_stats_records\x18\x01 \x03(\x0b\x32\x0f.LspStatsRecord\"\xbc\x01\n\x0eLspStatsRecord\x12\x13\n\x04name\x18\x01 \x02(\tB\x05\x82@\x02\x08\x01\x12\"\n\x13instance_identifier\x18\x02 \x02(\rB\x05\x82@\x02\x08\x01\x12\x1b\n\x0c\x63ounter_name\x18\x03 \x02(\tB\x05\x82@\x02\x08\x01\x12\x16\n\x07packets\x18\x04 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x14\n\x05\x62ytes\x18\x05 \x01(\x04\x42\x05\x82@\x02\x18\x01\x12\x13\n\x0bpacket_rate\x18\x06 \x01(\x04\x12\x11\n\tbyte_rate\x18\x07 \x01(\x04:C\n\x17jnpr_lsp_statistics_ext\x12\x17.JuniperNetworksSensors\x18\x05 \x01(\x0b\x32\t.LspStats'
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])


JNPR_LSP_STATISTICS_EXT_FIELD_NUMBER = 5
jnpr_lsp_statistics_ext = _descriptor.FieldDescriptor(
  name='jnpr_lsp_statistics_ext', full_name='jnpr_lsp_statistics_ext', index=0,
  number=5, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_LSPSTATS = _descriptor.Descriptor(
  name='LspStats',
  full_name='LspStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='lsp_stats_records', full_name='LspStats.lsp_stats_records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=94,
)


_LSPSTATSRECORD = _descriptor.Descriptor(
  name='LspStatsRecord',
  full_name='LspStatsRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LspStatsRecord.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202@\002\010\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='instance_identifier', full_name='LspStatsRecord.instance_identifier', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202@\002\010\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='counter_name', full_name='LspStatsRecord.counter_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202@\002\010\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packets', full_name='LspStatsRecord.packets', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202@\002\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='LspStatsRecord.bytes', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\202@\002\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_rate', full_name='LspStatsRecord.packet_rate', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='byte_rate', full_name='LspStatsRecord.byte_rate', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=285,
)

_LSPSTATS.fields_by_name['lsp_stats_records'].message_type = _LSPSTATSRECORD
DESCRIPTOR.message_types_by_name['LspStats'] = _LSPSTATS
DESCRIPTOR.message_types_by_name['LspStatsRecord'] = _LSPSTATSRECORD
DESCRIPTOR.extensions_by_name['jnpr_lsp_statistics_ext'] = jnpr_lsp_statistics_ext
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LspStats = _reflection.GeneratedProtocolMessageType('LspStats', (_message.Message,), {
  'DESCRIPTOR' : _LSPSTATS,
  '__module__' : 'lsp_stats_pb2'
  # @@protoc_insertion_point(class_scope:LspStats)
  })
_sym_db.RegisterMessage(LspStats)

LspStatsRecord = _reflection.GeneratedProtocolMessageType('LspStatsRecord', (_message.Message,), {
  'DESCRIPTOR' : _LSPSTATSRECORD,
  '__module__' : 'lsp_stats_pb2'
  # @@protoc_insertion_point(class_scope:LspStatsRecord)
  })
_sym_db.RegisterMessage(LspStatsRecord)

jnpr_lsp_statistics_ext.message_type = _LSPSTATS
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(jnpr_lsp_statistics_ext)

_LSPSTATSRECORD.fields_by_name['name']._options = None
_LSPSTATSRECORD.fields_by_name['instance_identifier']._options = None
_LSPSTATSRECORD.fields_by_name['counter_name']._options = None
_LSPSTATSRECORD.fields_by_name['packets']._options = None
_LSPSTATSRECORD.fields_by_name['bytes']._options = None
# @@protoc_insertion_point(module_scope)
