# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: npu_memory_utilization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='npu_memory_utilization.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1cnpu_memory_utilization.proto\x1a\x13telemetry_top.proto\"E\n!NetworkProcessorMemoryUtilization\x12 \n\x0cmemory_stats\x18\x01 \x03(\x0b\x32\n.NpuMemory\"k\n\tNpuMemory\x12\x12\n\nidentifier\x18\x01 \x02(\t\x12\"\n\x07summary\x18\x02 \x03(\x0b\x32\x11.NpuMemorySummary\x12&\n\tpartition\x18\x03 \x03(\x0b\x32\x13.NpuMemoryPartition\"_\n\x10NpuMemorySummary\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x11\n\tallocated\x18\x03 \x01(\x04\x12\x13\n\x0butilization\x18\x04 \x01(\x05\"\x83\x01\n\x12NpuMemoryPartition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x10\x61pplication_name\x18\x02 \x01(\t\x12\x17\n\x0f\x62ytes_allocated\x18\x03 \x01(\r\x12\x18\n\x10\x61llocation_count\x18\x04 \x01(\r\x12\x12\n\nfree_count\x18\x05 \x01(\r:S\n\x0enpu_memory_ext\x12\x17.JuniperNetworksSensors\x18\x0b \x01(\x0b\x32\".NetworkProcessorMemoryUtilization'
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])


NPU_MEMORY_EXT_FIELD_NUMBER = 11
npu_memory_ext = _descriptor.FieldDescriptor(
  name='npu_memory_ext', full_name='npu_memory_ext', index=0,
  number=11, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)


_NETWORKPROCESSORMEMORYUTILIZATION = _descriptor.Descriptor(
  name='NetworkProcessorMemoryUtilization',
  full_name='NetworkProcessorMemoryUtilization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='memory_stats', full_name='NetworkProcessorMemoryUtilization.memory_stats', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=122,
)


_NPUMEMORY = _descriptor.Descriptor(
  name='NpuMemory',
  full_name='NpuMemory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='NpuMemory.identifier', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='summary', full_name='NpuMemory.summary', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partition', full_name='NpuMemory.partition', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=231,
)


_NPUMEMORYSUMMARY = _descriptor.Descriptor(
  name='NpuMemorySummary',
  full_name='NpuMemorySummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='resource_name', full_name='NpuMemorySummary.resource_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='size', full_name='NpuMemorySummary.size', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allocated', full_name='NpuMemorySummary.allocated', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='utilization', full_name='NpuMemorySummary.utilization', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=328,
)


_NPUMEMORYPARTITION = _descriptor.Descriptor(
  name='NpuMemoryPartition',
  full_name='NpuMemoryPartition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NpuMemoryPartition.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='application_name', full_name='NpuMemoryPartition.application_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bytes_allocated', full_name='NpuMemoryPartition.bytes_allocated', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='allocation_count', full_name='NpuMemoryPartition.allocation_count', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='free_count', full_name='NpuMemoryPartition.free_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=462,
)

_NETWORKPROCESSORMEMORYUTILIZATION.fields_by_name['memory_stats'].message_type = _NPUMEMORY
_NPUMEMORY.fields_by_name['summary'].message_type = _NPUMEMORYSUMMARY
_NPUMEMORY.fields_by_name['partition'].message_type = _NPUMEMORYPARTITION
DESCRIPTOR.message_types_by_name['NetworkProcessorMemoryUtilization'] = _NETWORKPROCESSORMEMORYUTILIZATION
DESCRIPTOR.message_types_by_name['NpuMemory'] = _NPUMEMORY
DESCRIPTOR.message_types_by_name['NpuMemorySummary'] = _NPUMEMORYSUMMARY
DESCRIPTOR.message_types_by_name['NpuMemoryPartition'] = _NPUMEMORYPARTITION
DESCRIPTOR.extensions_by_name['npu_memory_ext'] = npu_memory_ext
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkProcessorMemoryUtilization = _reflection.GeneratedProtocolMessageType('NetworkProcessorMemoryUtilization', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKPROCESSORMEMORYUTILIZATION,
  '__module__' : 'npu_memory_utilization_pb2'
  # @@protoc_insertion_point(class_scope:NetworkProcessorMemoryUtilization)
  })
_sym_db.RegisterMessage(NetworkProcessorMemoryUtilization)

NpuMemory = _reflection.GeneratedProtocolMessageType('NpuMemory', (_message.Message,), {
  'DESCRIPTOR' : _NPUMEMORY,
  '__module__' : 'npu_memory_utilization_pb2'
  # @@protoc_insertion_point(class_scope:NpuMemory)
  })
_sym_db.RegisterMessage(NpuMemory)

NpuMemorySummary = _reflection.GeneratedProtocolMessageType('NpuMemorySummary', (_message.Message,), {
  'DESCRIPTOR' : _NPUMEMORYSUMMARY,
  '__module__' : 'npu_memory_utilization_pb2'
  # @@protoc_insertion_point(class_scope:NpuMemorySummary)
  })
_sym_db.RegisterMessage(NpuMemorySummary)

NpuMemoryPartition = _reflection.GeneratedProtocolMessageType('NpuMemoryPartition', (_message.Message,), {
  'DESCRIPTOR' : _NPUMEMORYPARTITION,
  '__module__' : 'npu_memory_utilization_pb2'
  # @@protoc_insertion_point(class_scope:NpuMemoryPartition)
  })
_sym_db.RegisterMessage(NpuMemoryPartition)

npu_memory_ext.message_type = _NETWORKPROCESSORMEMORYUTILIZATION
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(npu_memory_ext)

# @@protoc_insertion_point(module_scope)
