# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session_telemetry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import telemetry_top_pb2 as telemetry__top__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='session_telemetry.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17session_telemetry.proto\x1a\x13telemetry_top.proto\":\n\x0fServicesSession\x12\'\n\x11svcs_session_info\x18\x01 \x03(\x0b\x32\x0c.SessionInfo\"\xa6\x02\n\x0bSessionInfo\x12\x1f\n\x0csn_flow_info\x18\x01 \x03(\x0b\x32\t.FlowInfo\x12\x1e\n\x0fsn_svc_set_name\x18\x02 \x01(\tB\x05\x82@\x02\x08\x01\x12\x15\n\rsn_svc_set_id\x18\x03 \x01(\x04\x12\r\n\x05sn_id\x18\x04 \x01(\x04\x12\x10\n\x08sn_flags\x18\x05 \x01(\x04\x12\x11\n\tsn_alg_id\x18\x06 \x01(\x04\x12\x1c\n\x14sn_routing_path_type\x18\x07 \x01(\x04\x12\x1a\n\x12sn_session_timeout\x18\x08 \x01(\x04\x12\x10\n\x08sn_state\x18\t \x01(\x04\x12\x18\n\x10sn_sw_session_id\x18\n \x01(\x04\x12\x11\n\tsn_svc_id\x18\x0b \x01(\x04\x12\x12\n\nsn_offload\x18\x0c \x01(\x08\"\xcf\x02\n\x08\x46lowInfo\x12\x17\n\x08src_addr\x18\x01 \x01(\tB\x05\x82@\x02\x08\x01\x12\x17\n\x08\x64st_addr\x18\x02 \x01(\tB\x05\x82@\x02\x08\x01\x12\x16\n\x0e\x66low_direction\x18\x03 \x01(\r\x12\x10\n\x08src_port\x18\x04 \x01(\r\x12\x10\n\x08\x64st_port\x18\x05 \x01(\r\x12\x11\n\tsrc_is_v6\x18\x06 \x01(\x08\x12\x11\n\tdst_is_v6\x18\x07 \x01(\x08\x12\x11\n\tflow_type\x18\x08 \x01(\r\x12\x12\n\nflow_flags\x18\t \x01(\r\x12\x10\n\x08ip_proto\x18\n \x01(\r\x12\x14\n\x0cidle_timeout\x18\x0b \x01(\x04\x12\x17\n\x0f\x66low_packets_in\x18\x0c \x01(\x04\x12\x18\n\x10\x66low_packets_out\x18\r \x01(\x04\x12\x15\n\rflow_bytes_in\x18\x0e \x01(\x04\x12\x16\n\x0e\x66low_bytes_out\x18\x0f \x01(\x04:E\n\x12jnprScvsSessionExt\x12\x17.JuniperNetworksSensors\x18O \x01(\x0b\x32\x10.ServicesSession')
  ,
  dependencies=[telemetry__top__pb2.DESCRIPTOR,])


JNPRSCVSSESSIONEXT_FIELD_NUMBER = 79
jnprScvsSessionExt = _descriptor.FieldDescriptor(
  name='jnprScvsSessionExt', full_name='jnprScvsSessionExt', index=0,
  number=79, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_SERVICESSESSION = _descriptor.Descriptor(
  name='ServicesSession',
  full_name='ServicesSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='svcs_session_info', full_name='ServicesSession.svcs_session_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=106,
)


_SESSIONINFO = _descriptor.Descriptor(
  name='SessionInfo',
  full_name='SessionInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sn_flow_info', full_name='SessionInfo.sn_flow_info', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_svc_set_name', full_name='SessionInfo.sn_svc_set_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202@\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_svc_set_id', full_name='SessionInfo.sn_svc_set_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_id', full_name='SessionInfo.sn_id', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_flags', full_name='SessionInfo.sn_flags', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_alg_id', full_name='SessionInfo.sn_alg_id', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_routing_path_type', full_name='SessionInfo.sn_routing_path_type', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_session_timeout', full_name='SessionInfo.sn_session_timeout', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_state', full_name='SessionInfo.sn_state', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_sw_session_id', full_name='SessionInfo.sn_sw_session_id', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_svc_id', full_name='SessionInfo.sn_svc_id', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sn_offload', full_name='SessionInfo.sn_offload', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=403,
)


_FLOWINFO = _descriptor.Descriptor(
  name='FlowInfo',
  full_name='FlowInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_addr', full_name='FlowInfo.src_addr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202@\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_addr', full_name='FlowInfo.dst_addr', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\202@\002\010\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_direction', full_name='FlowInfo.flow_direction', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_port', full_name='FlowInfo.src_port', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_port', full_name='FlowInfo.dst_port', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_is_v6', full_name='FlowInfo.src_is_v6', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dst_is_v6', full_name='FlowInfo.dst_is_v6', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_type', full_name='FlowInfo.flow_type', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_flags', full_name='FlowInfo.flow_flags', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_proto', full_name='FlowInfo.ip_proto', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='idle_timeout', full_name='FlowInfo.idle_timeout', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_packets_in', full_name='FlowInfo.flow_packets_in', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_packets_out', full_name='FlowInfo.flow_packets_out', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_bytes_in', full_name='FlowInfo.flow_bytes_in', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_bytes_out', full_name='FlowInfo.flow_bytes_out', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=741,
)

_SERVICESSESSION.fields_by_name['svcs_session_info'].message_type = _SESSIONINFO
_SESSIONINFO.fields_by_name['sn_flow_info'].message_type = _FLOWINFO
DESCRIPTOR.message_types_by_name['ServicesSession'] = _SERVICESSESSION
DESCRIPTOR.message_types_by_name['SessionInfo'] = _SESSIONINFO
DESCRIPTOR.message_types_by_name['FlowInfo'] = _FLOWINFO
DESCRIPTOR.extensions_by_name['jnprScvsSessionExt'] = jnprScvsSessionExt
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServicesSession = _reflection.GeneratedProtocolMessageType('ServicesSession', (_message.Message,), {
  'DESCRIPTOR' : _SERVICESSESSION,
  '__module__' : 'session_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:ServicesSession)
  })
_sym_db.RegisterMessage(ServicesSession)

SessionInfo = _reflection.GeneratedProtocolMessageType('SessionInfo', (_message.Message,), {
  'DESCRIPTOR' : _SESSIONINFO,
  '__module__' : 'session_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:SessionInfo)
  })
_sym_db.RegisterMessage(SessionInfo)

FlowInfo = _reflection.GeneratedProtocolMessageType('FlowInfo', (_message.Message,), {
  'DESCRIPTOR' : _FLOWINFO,
  '__module__' : 'session_telemetry_pb2'
  # @@protoc_insertion_point(class_scope:FlowInfo)
  })
_sym_db.RegisterMessage(FlowInfo)

jnprScvsSessionExt.message_type = _SERVICESSESSION
telemetry__top__pb2.JuniperNetworksSensors.RegisterExtension(jnprScvsSessionExt)

_SESSIONINFO.fields_by_name['sn_svc_set_name']._options = None
_FLOWINFO.fields_by_name['src_addr']._options = None
_FLOWINFO.fields_by_name['dst_addr']._options = None
# @@protoc_insertion_point(module_scope)
